
services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-todo-app:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
